version: 5.1.0
variant: default
logo: /images/website/logo.svg
head:
    favicon: /images/website/favicon.svg
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        首页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
    type: disqus
    shortname: riverbankgrave
#donates:
#    -
#        type: afdian
#        url: ''
#    -
#        type: alipay
#        qrcode: ''
#    -
#        type: wechat
#        qrcode: ''
share:
    type: bdshare
sidebar:
    left:
        sticky: false
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: Shage_Jack
        author_title: Nur der Entschluß, den man auch für eine Willkür ansehen kann, nämlich daß man das Denken als solches betrachten wolle, ist vorhanden.
        location: Swamp
        avatar: /images/website/avatar.jpg
        avatar_rounded: true
        gravatar: 
        follow_link: https://www.zhihu.com/people/shagejack
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/shagejack
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/shage_jack
            Telegram:
                icon: fab fa-telegram
                url: https://t.me/Shage_Jack
            知乎:
                icon: fab fa-zhihu
                url: https://www.zhihu.com/people/shagejack
            哔哩哔哩:
                icon: fab fa-bilibili
                url: https://space.bilibili.com/6494682
            豆瓣:
                icon: fa-solid fa-book
                url: https://www.douban.com/people/shagejack
    -
        position: right
        type: toc
        index: false
        collapsed: false
        depth: 5
    -
        position: left
        type: recent_posts
    -
        position: left
        type: categories
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: left
        type: links
        links:
            TG频道 | 临川荒冢: https://t.me/riverbankgrave
    -
        position: left
        type: subscribe_email
        description: 
        feedburner_id: ''
    -
        position: left
        type: followit
        description: 
        action_url: ''
        verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
